name: 'Deployment to Google Cloud Functions'
on:
  push:
    branches:
      - 'release/*'
jobs:
  gcp-deploy:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - name: 'Use Node.js 14.5'
        uses: 'actions/setup-node@v1'
        with:
          node-version: '14.5'
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v2'
        with:
          fetch-depth: 0
      - name: 'Install dependencies'
        run: 'yarn install --frozen-lockfile'
      - name: 'Transpile'
        run: 'yarn build'
      - name: 'GCP Authenticate'
        uses: 'GoogleCloudPlatform/github-actions/setup-gcloud@master'
        with:
          project_id: '${{ secrets.GCP_PROJECT_ID }}'
          service_account_email: '${{ secrets.GCP_SA_EMAIL }}'
          service_account_key: '${{ secrets.GCP_SA_KEY }}'
          export_default_credentials: true
      - name: 'Deploy to Cloud Functions'
        run: |
          gcloud functions deploy cancello \
          --region ${{ secrets.GCP_REGION }} \
          --runtime nodejs12 \
          --source dist/ \
          --trigger-http \
          --quiet
