name: 'Deployment to Google Cloud Functions'
on:
  push:
    branches:
      - 'release/*'
jobs:
  gcp-deploy:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v2'
        with:
          ref: 'main'
      - name: 'Transpile'
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: 'GCP Authenticate'
        uses: 'GoogleCloudPlatform/github-actions/setup-gcloud@master'
        with:
          project_id: '${{ secrets.GCP_PROJECT_ID }}'
          service_account_email: '${{ secrets.GCP_SA_EMAIL }}'
          service_account_key: '${{ secrets.GCP_SA_KEY }}'
          export_default_credentials: true
      - name: 'Configure docker to use the gcloud cli'
        run: 'gcloud auth configure-docker --quiet'
      - name: 'Deploy to Cloud Functions'
        run: |
          gcloud beta functions -quiet \
            deploy cancello \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --runtime nodejs12 \
            --source dist/ \
            --trigger-http
