name: 'Deployment to Google Cloud Functions'
on:
  push:
    branches:
      - 'main'
env:
  GCP_PROJECT_ID: '${{ secrets.GCP_PROJECT_ID }}'
  GCP_REGION: '${{ secrets.GCP_REGION }}'
  IMAGE: 'asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/foobar:${{ github.sha }}'
jobs:
  gcp-deploy:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v2'
        with:
          ref: 'main'
      - name: 'GCP Authenticate'
        uses: 'GoogleCloudPlatform/github-actions/setup-gcloud@master'
        with:
          project_id: '$GCP_PROJECT_ID'
          service_account_key: '${{ secrets.GCP_SA_KEY }}'
          export_default_credentials: true
      - name: 'Configure docker to use the gcloud cli'
        run: 'gcloud auth configure-docker --quiet'
      - name: 'Build a docker image'
        run: 'docker build . -t cancello'
      - name: 'Push the docker image'
        run: './docker-push.sh'
      - name: 'Deploy to Cloud Run'
        run: |
          asof=`date +%Y%m%d%H%M%S`
          IMAGE=gcr.io/$GCP_PROJECT_ID/cancello:${asof}
          docker build . -t $IMAGE
          docker push $IMAGE
          gcloud run deploy cancello \
            --image $IMAGE \
            --platform managed \
            --region $GCP_REGION \
            --project $GCP_PROJECT_ID \
            --port 8080 \
            --quiet
