name: 'Deployment to Google Cloud Functions'
on:
  push:
    branches:
      - 'release/*'
jobs:
  gcp-deploy:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v2'
        with:
          ref: 'main'
      - name: 'GCP Authenticate'
        uses: 'GoogleCloudPlatform/github-actions/setup-gcloud@master'
        with:
          project_id: '$GCP_PROJECT_ID'
          service_account_email: '$GCP_SA_EMAIL'
          service_account_key: '$GCP_SA_KEY'
          export_default_credentials: true
      - name: 'Configure docker to use the gcloud cli'
        run: 'gcloud auth configure-docker --quiet'
      - name: 'Deploy to Cloud Functions'
        run: |
          gcloud beta functions deploy cancello \
            --runtime nodejs12 \
            --region $GCP_REGION \
            --project tegebu \
            --source dist/ \
            --trigger-http \
            --quiet
    env:
      GCP_PROJECT_ID: '${{ secrets.GCP_PROJECT_ID }}'
      GCP_REGION: '${{ secrets.GCP_REGION }}'
      GCP_SA_EMAIL: '${{ secrets.GCP_SA_EMAIL }}'
      GCP_SA_KEY: '${{ secrets.GCP_SA_KEY }}'
